### ISSUE TITLE
"The owner of this website has banned your access based on your browser's signature"

### ISSUE THREAD

**Issue by freakedenough** [atauenis/webone#109]
Trying to access www.heute.at or other Cloudflare-protected sites results in a 1010 error, using stock configuration.
"The owner of this website has banned your access based on your browser's signature"
![Unbenannt](https://github.com/atauenis/webone/assets/93607470/201a9d56-2272-4cec-911a-bb5f08c39d7c)
using Netscape 0.91 Beta.

Any tips how to prevent this?

**Comment by atauenis** [comment]
Set in configuration file:
```INI
[Server]
UserAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

[ForceHttps]
heute.at
www.heute.at
```
At least, in Netscape 3.04 helps to bypass Cloudflare test. Try in 0.91b. Hope, also will be useful.

**Comment by freakedenough** [comment]
It works, thank you very much!
