### ISSUE TITLE
Webone can’t install on Debian armhf bookworm: issue with libicu72

### ISSUE THREAD

**Issue by faucon2001** [atauenis/webone#111]
Hi,

i am trying to install webone 0.16.2 armhf on a Raspberry Pi 400 running on Bookworm 32 bit, without success.
Apt install complaints that webone depends on libicu 52 to 70.
But in Bookworm, libicu is in version 72.
What can I do?

regards,

Philippe

**Comment by way5** [comment]
Hi @faucon2001 .
I'd recommend you to check this [topic](https://github.com/way5/docker-webone/issues/2).
there is installation script you could use [webone.arm.sh](https://github.com/way5/webone/blob/sandbox/autoinstall/webone.arm.sh). 
Also please post the compiling commands and console output if you'd like us to check what's going on in your exact situation.

~

**Comment by way5** [comment]
I've just updated the [script](https://github.com/way5/webone/blob/sandbox/autoinstall/webone.linux.sh). 
Let me know if there is any issue.

~

**Comment by atauenis** [comment]
Thanks for bug report. Seems that on Debian 12/13/sid and Ubuntu 23.04/23.10/24.04 there is no more `libicu70` package. I'll fix the dependency list soon.

**Comment by faucon2001** [comment]
The script worked well and webone is now running ok with Bookworm.
Thanks,

**Comment by way5** [comment]
Good news @faucon2001 !
Glad that it helped you.

**Comment by atauenis** [comment]
Fixed in v0.16.3.
