### ISSUE TITLE
WebOne not working AT ALL on linux

### ISSUE THREAD

**Issue by pootispenserhere4723** [atauenis/webone#116]
hello, i installed WebOne on my linux mint 21.3 install and connected the proxy to a Windows XP VM, the problem is that upon doing a random search the proxy doesn't seem to be working due to the console not displaying anything and the VM failing the search

**Comment by atauenis** [comment]
`$ sudo service webone status`? If it's running, probably Windows XP VM don't see host applications due to incorrect network configuration. This verifiable by pinging the host from Windows XP VM.

**Comment by pootispenserhere4723** [comment]
And how could i fix the network configuration then?

**Comment by atauenis** [comment]
https://github.com/atauenis/webone/wiki/Using-with-virtual-machines

**Comment by pootispenserhere4723** [comment]
It works WONDERS now!!! Thank you!!
