### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by my05** [atauenis/webone#130]
Hi, as i did not want to mix the raspberry5 issues with W10 issues i opened a new ticket.

i started the win64 process on my w10 machine and it worked perfectly well at first, but when i tried to access wikipedia from the IE 6 installation on my retro machine, the W10 process shows this in the console:

Idle process killed
<done (connection close).
etc

Meanwhile a dialogue pops up saying:

'convert.exe'

The code execution cannot proceed because VCOMP140.DLL was not found. Reinstalling the program may fix this problem

**Comment by tomrow** [comment]
You are missing a component from the Microsoft Visual C++ runtime, you can get a copy from here:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

**Comment by atauenis** [comment]
Yes, ImageMagick is requiring VC++ 2022 Redistributable to work. Added to FAQ:
https://github.com/atauenis/webone/wiki/Windows-installation#troubleshooting
