### ISSUE TITLE
Broad regex in default config

### ISSUE THREAD

**Issue by grawity** [atauenis/webone#137]
I'm using WebOne with an iPhone 6 that runs iOS 12, with user agent:

> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_5_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

WebOne automatically detects it as needing WEBP-to-PNG conversion, even though it doesn't appear to be in the config.

It turns out that the `.*rv:([0-5].)|([6][0-4])` regex in the default config file happens to match `AppleWebKit/605.1.15`. I'm not sure if it's _meant to_ match every instance of `6[0-4]` in any header? I suspect it was supposed to say `rv:([0-5].|6[0-4])` with the `|` inside the group.

**Comment by atauenis** [comment]
Thanks for report. Yes, the mask used in WebOne 0.17.1 matches Mobile Safari 12 UA too even however it does not containing `rv:`. Also it matches Firefox 100+, but this can be easily fixed by replacing the mask with `rv:([0-5]([\.]|[0-9]\.)|6[0-4])`. I'll include the fix in WebOne 0.17.2.
