### ISSUE TITLE
Run without administrator rights in Windows

### ISSUE THREAD

**Issue by jblang** [atauenis/webone#14]
I prefer not to give software I downloaded more rights than required. Here is a way to get WebOne to run without admin rights:

https://stackoverflow.com/questions/14962334/httplistenerexception-access-denied-for-non-admins

I found it was also necessary to manually open the port in my firewall inbound rules.

**Comment by atauenis** [comment]
Thank you, I haven't know this trick.
I'll add workaround for user rights support in next release.

**Comment by atauenis** [comment]
Just leave here as a bookmark for future: https://www.cyberforum.ru/csharp-beginners/thread1595061-page2.html ([Translated to English](https://translate.googleusercontent.com/translate_c?depth=1&pto=aue&rurl=translate.google.com&sl=ru&sp=nmt4&tl=en&u=https://www.cyberforum.ru/post8406955.html&usg=ALkJrhj3AaJEeKf5ZJ1rw18kYffo7vJF0Q)).

The similar problem is that user need to add a firewall rule to open Port 80. So if we're configuring system to allow non-admin users to launch WebOne, why not to also perform firewall configuration.
