### ISSUE TITLE
Documentaton about installing certificate in Windows 3.1 is full of lies and jibberish.

### ISSUE THREAD

**Issue by steviator** [atauenis/webone#152]
"Microsoft Internet Explorer for Windows 3.11

Seems that it lacks support for installing CAs from files. But it is still possible to install it directly to registry. Download the root certificate file, and open it in an hexadecimal editor. Then run MSIE Registry Editor, located at C:\WINDOWS\SYSTEM\REGEDT16.exe. Open HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CertificationAuthorities\, and create a branch for WebOne Certificate Authority XXX, where XXX is your CA number. The CACert key is place for contents of your WebOneCA.crt file (nearly 1000 bytes).

Hint: you can copy HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CertificationAuthorities\WebOne Certificate Authority XXX registry branch contents from an machine with Windows 95 or NT 4.0, where the certificate is already installed. REGEDT16 can import REGEDIT 4.0 .REG files."

1) What is a "branch"... you can create a key, string, binary value or dword. There is nothing callled a branch in the registry and never has been

2) What is the XXX number supposed to be? Do I make it up? 

3) What is a CA number? is it the same as XXX? where do I find it? 

4) What is a CAcert key? Am I supposed to make another key? Are we calling them branches or keys?

5) You can't copy the key from the registry of a Windows 95 machine, because it doesn't store them in the place specfied

Could someone please rewrite this section into something that makes sense? it's impossible to follow the above instructions.

**Comment by atauenis** [comment]
1. This is translation mistake (English is not my native language, sorry). I'll fix this. I'm meaning here "add a key (with folder icon) with specific values (with document icon)".
2. The `CA number` is the number from certificate name visible in certificate contents. Open the certificate in any software (Windows 95+ can this) to view it.
3. The `CA number` is `XXX` and `XXX` is the `CA number`.
4. `CAcert` is the body of the CA certificate file, copied onto the registry as is, byte by byte in hexadecimal format.
5. I'm missed that it's need to have MSIE 3, not MSIE 4 or 5. IE 4/5 are storing certificates elsewhere. And Win95/NT4 can run IE 3.0 (95B have it out of box, some builds of NT4 also, and on all it can be installed manually).

So: just run Win95 (or NT4) + IE3 somewhere, import the certificate, make sure that SSL is working via IE 3.0, then export `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\CertificationAuthorities\WebOne Certificate Authority XXX` (the number is unique, will work only with your WebOne installation), and import it via REGEDT16 on your Win3.11.

**Comment by steviator** [comment]
I'm now downloading a Windows 95 RTM, and creating a new VM for the express purpose of extracting the certificate so that I can export it as a .reg file, which I will then place here in the hopes that I can save somebody else from going through this ridiculous process.

**Comment by steviator** [comment]
Okay, I installed Windows 95 RTM, the earlest version of Windows, and it still comes with IE4 installed. 

Can you please give some instructions that aren't lies. I've wasted hours of my time on this.

**Comment by atauenis** [comment]
> After scouring the internet, I have been unable to find a Windows installation disk that works which isn't bundled with a later version of IE than you claim will work.

https://winworldpc.com/product/windows-95/osr-2
Do not use OSR 2.5. All other Win95 builds (except OSR 2.5) does not containing IE 4.0 (some even MSIE at all).

> can you please upload the .reg file that would install the required certificate into windows 3.1

It's not possible because each WebOne installation is containing an unique root certificate (the `ssl.crt` file).
