### ISSUE TITLE
edit http:/ to http:// in set edits

### ISSUE THREAD

**Issue by winterhard** [atauenis/webone#18]
Nice work! I am trying to get it working with Atari Highwire browser. Cannot set a proxy so I use 
 `http://127.0.01/http://atari-forum.com` 
The browser changes the double-slash to single-slash so the proxy tries
`GET /http:/atari-forum.com`
and fails.
How can I add a redirect to fix this?

**Comment by atauenis** [comment]
Seems, there is a bug in v0.10.3. By the edit set syntax, such edit should look this:
```
[Edit:^http:/http://atari-forum.com]
AddRedirect=http://%Proxy%/http://http://atari-forum.com/%UrlNoDomain%
```
However, on attempt to open http://127.0.01/http://atari-forum.com we're got a 500 error:

> 500 InternalServerError
> An error occured: System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
> at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
> at System.Uri..ctor(String uriString)
> at WebOne.Transit..ctor(HttpListenerRequest ClientRequest, HttpListenerResponse ClientResponse, LogWriter Log) in Transit.cs:line 431

So it's need to some rewrite area around 429-442 lines of Transit.cs to fix the bug.

**Comment by atauenis** [comment]
Fixed the bug, so v0.10.4 should open http://127.0.01/http:/atari-forum.com (exactly, http://127.0.01:8080/http:/atari-forum.com as I've changed default port in the v0.10.4) correctly.
![2021-01-22_17-18-17](https://user-images.githubusercontent.com/4800266/105501968-f1d52800-5cd5-11eb-81b6-da7640d73a46.png)

**Comment by winterhard** [comment]
Great. Can you please add v.0.10.4 to Releases?

**Comment by atauenis** [comment]
It is currently not ready, so I'll add v0.10.4 to Releases when complete it. Probably in early February.
