### ISSUE TITLE
Need to adapt Wikipedia and IMDb

### ISSUE THREAD

**Issue by EgorKuzevanov** [atauenis/webone#28]
Hello, dear Atauenis! Can you adapt Russian/English Wikipedia and imdb.com for the following browsers?:

- Internet Explorer (versions from 3.0 to 11.0)
- Netscape (versions from 3.04 to 9.0.0.6)
- Mozilla Firefox (versions from 1.0 to 48.0.2)
- Mozilla Suite (versions from 0.9.4 to 1.7.13)
- SeaMonkey (versions from 1.0 to 2.40)
- K-Meleon (versions from 1.1.5 to 1.5.4)
- Opera Presto (versions from 3.51 to 12.18)
- Opera Blink (versions from 15 to 36)
- Google Chrome (versions from 1.0.154.65 to 49.0.2623.112)
- Safari for Windows (versions from 3.1 to 5.1.7)

Thank you in advance.

**Comment by atauenis** [comment]
Hello, Egor!

What you mean? Wikipedia is opening semi-correctly in most of browsers. At least, the text is displaying correctly.

Probably it is need to rewrite CSS and JS files for these browsers to fix styling and restore link preview. I don't know when I'll write them, as it needs time which I have no.

Russian Wikipedia needs `OutputEncoding=Windows` option in webone.conf to display in IE <4.0, Netscape <4.5 as these browsers don't understand Unicode.

![Netscape 3 ruwiki](https://user-images.githubusercontent.com/4800266/110913377-218fcc00-8326-11eb-9ba8-70802cb6b202.png)

IMDb, yes, is showing as regular text, so this needs to be investigated. Probably I'll fix this in next version.

**Comment by atauenis** [comment]
Update: seems, it was an error of Amazon anti-bot checks. Reloaded the http://www.imdb.com/ page after 5 mins, and the text appears. So the situation is similar to Wikipedia.

If you know CSS, you may write a new stylesheet, and [make](https://github.com/atauenis/webone/wiki/Sets-of-edits) a redirect from real CSS file to your (needs to be hosted everywhere, even may be on local Apache/Nginx/IIS/sHTTPs).
