### ISSUE TITLE
Disable JavaScript and CSS for individual sites

### ISSUE THREAD

**Issue by EgorKuzevanov** [atauenis/webone#29]
How to disable JavaScript and CSS for individual sites in WebOne? Needed for correct display of Wikipedia in the following browsers:

- Internet Explorer 4.01 SP2
- Netscape 4.80
- Mozilla Firefox 1.0
- SeaMonkey 1.0
- Opera 8.54

Thank you in advance.

**Comment by atauenis** [comment]
Try to ban via Edits:

``` INI
[Edit:http://[a-z]*.wikipedia.org/w/load.php]
OnContentType=text/javascript
AddRedirect=about:blank

[Edit:http://[a-z]*.wikipedia.org/w/load.php]
OnContentType=text/css
AddRedirect=about:blank
```
