### ISSUE TITLE
Wikipedia scripts and styles keep loading even after being blocked

### ISSUE THREAD

**Issue by EgorKuzevanov** [atauenis/webone#31]
I added the following code to the webone.conf config file to block JavaScript and CSS on Wikipedia:

```
[Edit:http://[a-z]*.wikipedia.org/w/load.php]
OnContentType=text/javascript
AddRedirect=about:blank

[Edit:http://[a-z]*.wikipedia.org/w/load.php]
OnContentType=text/css
AddRedirect=about:blank
```

but scripts and styles continue to load anyway, as in the screenshot: https://b.radikal.ru/b23/2103/f3/554da5d31ebft.jpg
Host system: Windows 10 Enterprise (x64) v1903
WebOne version: 0.10.6 Full (x86)
Guest system: Windows XP Professional SP3
Guest browser: Internet Explorer 8

**Comment by atauenis** [comment]
Try to replace `[Edit:http://[a-z]*.wikipedia.org/w/load.php]` with `[Edit:http://[a-z]*.wiki[a-z]*.[a-z]*/]`.

В общем, надо подобрать маску RegExp, отвечающую адресу скриптов и стилей у Википедии. Я на скорую руку ответил в #29 , мог ошибиться.

**Comment by atauenis** [comment]
This should be used:

``` INI

; murder JS & CSS files
[Edit:http://[a-z]*.wiki[a-z]*.[a-z]*/w/load.php]
AddRedirect=about:blank

; murder inline CSS
[Edit:http://[a-z]*.wiki[a-z]*.[a-z]*/]
AddFind=<style data-mw-deduplicate=[a-zA-Z0-9=":\.;\-\+ {}()#,%@/_>]*</style>
AddReplace=<!--Wikipedia CSS removed-->
```
