### ISSUE TITLE
The ability to load login:password from a passwd file

### ISSUE THREAD

**Issue by georgebohnisch** [atauenis/webone#41]
It would be nice to have the ability to set a password file path in the configuration file that contained a list of login:password entries. As an example:

Config File:
```
AuthenticateFile=/etc/WebOne/passwd
```

`/etc/WebOne/passwd`

```
user1:password
user2:password
user3:password
```

This would give the ability for basic user management.

**Comment by atauenis** [comment]
As the nearest version of WebOne (0.11) will have support for multiple configuration files, added similar, but different syntax:
```INI
; default webone.conf:
[Include:%WOConfigDir%/*.conf]
```
```INI
; my.conf in WebOne's directory on Windows or /etc/webone.conf.d/my.conf on Linux/Mac:
[Authenticate]
user1:password
user2:password
user3:password
```

Also it is possible to use semi-old syntax, all `Authenticate=login:password` lines in `[Server]` section of any loaded configuration file will be treated as registration of a new user. Only `--proxy-authenticate` argument of program will override login/password list at all.

**Comment by georgebohnisch** [comment]
Does traffic get logged according to the user that performed the request? If not that would be a wonderful addition.

**Comment by atauenis** [comment]
Currently no. Log file is saving user name only when it is incorrect. Traffic dump files are containing only raw header (`Proxy-Authorization: Basic dXNlcjpwYXNz`). It is easy to decrypt, but it still not a good user identificator for debug purposes.

I'm too think that it will be good if both log and dumps will contain both client IP and username.
