### ISSUE TITLE
systemd dependancy makes dockerizing difficult

### ISSUE THREAD

**Issue by zefie** [atauenis/webone#45]
Readme states:
`Basically, WebOne requiring only one package to be installed. It is dotnet-runtime-3.1`

But this is not quite true, as it also seems to depend on systemd, as per:

```
Setting up webone (0.11.0) ...
/var/lib/dpkg/info/webone.postinst: 19: /var/lib/dpkg/info/webone.postinst: systemctl: not found
/var/lib/dpkg/info/webone.postinst: 20: /var/lib/dpkg/info/webone.postinst: systemctl: not found
dpkg: error processing package webone (--configure):
 installed webone package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 webone
```

Anyone else attempting to dockerize WebOne, until checks are added to webone.postinst, can use this workaround:
```
        if [ ! -f /bin/systemctl ]; then
                # Create dummy systemctl
                touch /bin/systemctl
                chmod +x /bin/systemctl
        fi
```

**Comment by atauenis** [comment]
Fixed installation scripts (in Git `master`), so they are no longer requiring `systemctl`.

Previously I've thought that systemd is present in all systems as regular installation wizard (from official CD/DVD images) don't allow to install system without it.
