### ISSUE TITLE
matrix web client

### ISSUE THREAD

**Issue by manchelsi** [atauenis/webone#58]
Есть ли возможность запустить веб клиенты matrix, к примеру http://app.element.io/#/welcome
пробовал его и несколько других, получаю белый экран.

**Comment by atauenis** [comment]
Здравствуйте! С большой вероятностью, оно не заработает, поскольку это сложное веб-приложение. Но шансы на удачу, например, в Firefox 30 или Chrome 18 каком-нибудь есть. Пока я не пробовал. В браузерах уровня Firefox 2 или MSIE 6 оно точно работать не будет.

**Comment by manchelsi** [comment]
Спасибо за ответ. По всей видимости сложный js: Firefox, Chrome и форки на их основе так же не справились.
