### ISSUE TITLE
dotnet 3.1 is obsolete (and has no install package for Ubuntu 22.10)

### ISSUE THREAD

**Issue by prosper00** [atauenis/webone#62]
is there any way to run webone using dotnet 6.0?

**Comment by atauenis** [comment]
Currently the only way is to rebuild from sources, after editing `TargetFramework` version in `WebOne.csproj`.
I'm planning to release WebOne 0.12 using .NET 6.0.

**Comment by atauenis** [comment]
https://github.com/atauenis/webone/releases/tag/v0.12b1 - should be compatible with Ubuntu 22.xx.
