### ISSUE TITLE
Latest working version for XP

### ISSUE THREAD

**Issue by TheElf01** [atauenis/webone#71]
Hi,  WebOne 0.9.3 is latest to work on XP, or i miss another build?

thanks a lot

**Comment by atauenis** [comment]
Latest version of WebOne for XP/Vista was 0.9.3. In 2020 websites quickly moved to newer TLS ciphers available only on Windows 7+, and I've dropped any support for previous Windows versions (and for Mono Runtime on Linux too, which even not have any TLS 1.2 support at all).

Even if recompile latest code base back for .NET Framework 4.0, it will not open any web sites (without ProxHTTPSproxyMII in parallel with WebOne :) ).

XP clients are still supported by all latest WebOne versions.
