### ISSUE TITLE
CONNECT method results in HTTP 400 error

### ISSUE THREAD

**Issue by Aminuxer** [atauenis/webone#82]
When WebOne proxy specified as HTTPS-proxy for old browser (like Opera 9 for example) 
i got error in browser:
Bad Request (Invalid url: WEBSITE_ADDREESS:8080WEBSITE_ADDREESS:443)

In tcpdump i see CONNECT method and http-code 400.

**Comment by atauenis** [comment]
Currently the CONNECT method (a.k.a. HTTP Secure Proxy) is not supported by WebOne. So it's need to configure Opera to use only plain HTTP.
![Opera 964](https://user-images.githubusercontent.com/4800266/217918902-e4ffaf3a-050c-439f-a4e4-97c0553e714e.png)

**Comment by atauenis** [comment]
Fixed in v0.16 Beta. Now HTTPS is working too. Not quite stable, but working.
