### ISSUE TITLE
Latest Webone HTTPS proxy problem

### ISSUE THREAD

**Issue by way5** [atauenis/webone#88]
Hi @atauenis !
Since the version 0.15 I found that HTTPS proxies doesn't work for my setup anymore. In a few words:
- HTTPS proxy server is set to XXX.XXX.XXX.XXX:8080 and perfectly available in my network. I have to mention HTTP proxy is set to the same XXX.XXX.XXX.XXX:8080 and works well.
![Picture 2](https://user-images.githubusercontent.com/8507413/228047939-230bb9f7-4a37-4e61-9552-d585be75812b.png)

- Once I open SSL connection it fails like so: 
![Picture 3](https://user-images.githubusercontent.com/8507413/228047737-5f2b977a-6c6a-441c-86c3-956569bc2c41.png)

- When I disable HTTPS proxy it acts as expected:
![Picture 1](https://user-images.githubusercontent.com/8507413/228047881-dfd0f242-9d48-4967-a941-a556756cf6e6.png)

I might miss something here, please advice.

~ Thanks

**Comment by atauenis** [comment]
See: https://github.com/atauenis/webone/issues/82

None of WebOne versions were designed to work over true HTTPS. All are converting HTTP requests from old browsers to HTTPS connections to modern sites. It's strange that before the "Secure Web Proxy" option worked with WebOne. Probably you entered URL with HTTP://, not HTTPS://, and it opened via WebOne (just if the Secure Proxy option is not set). If now the browser don't allow open osxdaily.com via HTTP (redirecting to HTTPS even before any network connection attempt), somewhy it added the domain to [HSTS list](https://github.com/atauenis/webone/wiki/HSTS).

I'm planning to implement real Secure HTTP support in some of future releases. This will be a very large work (needs rewriting ~50% of server code, including manual support for Keep-Alive and other difficult stuff over raw TCP sockets/Streams), but not impossible.
