### ISSUE TITLE
Memory leak 0.16-beta1

### ISSUE THREAD

**Issue by way5** [atauenis/webone#94]
Hi @atauenis,
this looks to me as like a severe memory leak:

![IMG01](https://github.com/atauenis/webone/assets/8507413/a72345e0-ea69-4746-aaf7-3f69de98f2b3)
![IMG02](https://github.com/atauenis/webone/assets/8507413/1da56261-e566-41a1-8155-1eb872644a48)

Any logs you'd like to see?

Just started the server, it was used by the only client a few hours today.

~

**Comment by atauenis** [comment]
Hmm, very strange, will investigate.
1. Does the problem appear in v0.15.3?
2. Does log contains lines like `<Done (connection close).` or just `<Done.`? The "pending requests" counter is currently not working in this beta, and only the log is a indicator of reaching "entry" and "exit" points of code.
3. Do you used SSL or only plain HTTP connections?
4. Does log contains strange lines, like `>GET //////////////// (127.0.0.1)`? I've seen such problem at early stages of debug, but probably fixed it as haven't repeated anymore.

**Comment by way5** [comment]
1. Nope, this is the very first version that's behave like that. 
2. It contains both. I've attached the log below, the last 3 days long.

[webone.log](https://github.com/atauenis/webone/files/11766965/webone.log)

4. Yes, the proxy provides HTTPS connection on port 8081 as by defaults
5. Haven't seen that.

Platform:
- Linux 6.1.24-meson64 #2 SMP PREEMPT Thu Apr 13 14:55:40 UTC 2023 aarch64 GNU/Linux 

.NET:
```
# dotnet --list-sdks
7.0.302 [/root/.dotnet/sdk]

# dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.5 [/root/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.5 [/root/.dotnet/shared/Microsoft.NETCore.App]

```

**Comment by atauenis** [comment]
Thanks, it's enough for debugging. Seems that I've some improperly implemented resource freeing on `<Done (connection close)` part of processing.

Also I'm see that SSL server doesn't work because no write access to `/etc/webone/ssl.*` (this is fixed on deb/rpm packages by `chmod` on them).

**Comment by way5** [comment]
Yes, I've missed the chmod in my installation script 🙃 
Thanks!

**Comment by way5** [comment]
Also, there is an issue with date formats in webone.config.  

```
...
Jun 17 12:49:32 webone[2176]: Using event log file /var/log/webone.log.
Jun 17 12:49:32 webone[2176]: Error while loading configuration: String '"01.01.1970 00:00 +0"' was not recognized as a valid DateTime.
...
Jun 17 12:51:17 systemd[1]: Started WebOne HTTP Proxy Server.
Jun 17 12:51:17 webone[2228]: WebOne HTTP Proxy Server 0.16.0-beta1
Jun 17 12:51:17 webone[2228]: https://github.com/atauenis/webone
Jun 17 12:51:18 webone[2228]: Using custom configuration from /etc/webone/webone.conf.
Jun 17 12:51:18 webone[2228]: Using configuration file /etc/webone/webone.conf.
Jun 17 12:51:18 webone[2228]: Using configuration file /etc/webone/codepage.conf.
Jun 17 12:51:18 webone[2228]: Using event log file /var/log/webone.log.
Jun 17 12:51:18 webone[2228]: Error while loading configuration: String '31.12.2070 23:59:59 +0' was not recognized as a valid DateTime.
...
```

Fix:

```
SslRootValidAfter=01/01/1970 00:00:00 +0:00
SslRootValidBefore=12/31/2070 23:59:00 +0:00
```

Latest webone.log is attached below. User agent Safari 4.1.3

[webone.log](https://github.com/atauenis/webone/files/11779836/webone.log)
