### ISSUE TITLE
0.16.0beta2 Segmentation fault on armhf linux

### ISSUE THREAD

**Issue by tomrow** [atauenis/webone#98]
I can't run this on a Raspberry Pi Zero W. All it outputs to the terminal emulator is "Segmentation fault". Not enough memory perhaps, or maybe this requires a newer version of the ARM instruction set?

**Comment by way5** [comment]
Hi @tomrow 
Please check the following topic:

https://github.com/atauenis/webone/discussions/75

Unfortunately, .NET doesn't support ARMv6 CPUs.

**Comment by tomrow** [comment]
Just as I thought.
I was using the precompiled ARMHF DEB file.

**Comment by tomrow** [comment]
.NET does not support ARMv6
