### ISSUE TITLE
304 NotModified from pypi.org returns unknown/unknown Content-Type

### ISSUE THREAD

**Issue by WunderWungiel** [atauenis/webone#99]
Hello
If I visit pypi.org for second time, it returns 304 NotModified but with incorrect unknown/unknown Content-Type. This breaks pip package manager. When I visit it normally, natively through browser and I get 304 it doesn't return any Content-Type (which is ok and works with pip) but unknown/unknown breaks it. Is there any fix? Or how can I clear WebOne cache, so it will forcibly redownload site contents (and so give 200 instead of 304?)?

**Comment by atauenis** [comment]
This was a design error in WebOne 0.15.3 and 0.16 Beta 2. Now I've fixed it, so the next version will not have this bug.
